/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TotemIndexRouteImport } from './routes/totem.index'
import { Route as TotemProntoRouteImport } from './routes/totem.pronto'
import { Route as TotemConfirmarRouteImport } from './routes/totem.confirmar'
import { Route as TotemBuscarRouteImport } from './routes/totem.buscar'
import { Route as MovimentacaoHistoricoRouteImport } from './routes/movimentacao.historico'
import { Route as MovimentacaoSlugRouteImport } from './routes/movimentacao.$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthUpdatePasswordRouteImport } from './routes/auth_.update-password'
import { Route as AuthRecoverRouteImport } from './routes/auth_.recover'
import { Route as ATokenRouteImport } from './routes/a.$token'
import { Route as AuthenticatedServicesRouteImport } from './routes/_authenticated/services'
import { Route as AuthenticatedReviewsRouteImport } from './routes/_authenticated/reviews'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMenuRouteImport } from './routes/_authenticated/menu'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/_admin/route'
import { Route as AuthenticatedMovimentacaoIndexRouteImport } from './routes/_authenticated/movimentacao.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AuthenticatedRelatoriosMovimentacoesRouteImport } from './routes/_authenticated/relatorios.movimentacoes'
import { Route as AuthenticatedOnboardingServicosRouteImport } from './routes/_authenticated/onboarding.servicos'
import { Route as AuthenticatedOnboardingProntoRouteImport } from './routes/_authenticated/onboarding.pronto'
import { Route as AuthenticatedOnboardingPerfilRouteImport } from './routes/_authenticated/onboarding.perfil'
import { Route as AuthenticatedOnboardingDisponibilidadeRouteImport } from './routes/_authenticated/onboarding.disponibilidade'
import { Route as AuthenticatedOnboardingBemVindoRouteImport } from './routes/_authenticated/onboarding.bem-vindo'
import { Route as AuthenticatedAppointmentsNewRouteImport } from './routes/_authenticated/appointments.new'
import { Route as AuthenticatedAdminReconciliarRouteImport } from './routes/_authenticated/_admin/reconciliar'
import { Route as AuthenticatedAdminGhlTestRouteImport } from './routes/_authenticated/_admin/ghl-test'
import { Route as AuthenticatedAppointmentsNewIndexRouteImport } from './routes/_authenticated/appointments.new.index'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksSyncGhlRouteImport } from './routes/api/public/hooks/sync-ghl'
import { Route as ApiPublicHooksSendRemindersRouteImport } from './routes/api/public/hooks/send-reminders'
import { Route as AuthenticatedAppointmentsNewServicosRouteImport } from './routes/_authenticated/appointments.new.servicos'
import { Route as AuthenticatedAppointmentsNewRevisaoRouteImport } from './routes/_authenticated/appointments.new.revisao'
import { Route as AuthenticatedAppointmentsNewClienteRouteImport } from './routes/_authenticated/appointments.new.cliente'
import { Route as AuthenticatedAppointmentsNewAgendaRouteImport } from './routes/_authenticated/appointments.new.agenda'
import { Route as AuthenticatedAdminRelatoriosAgendamentosRouteImport } from './routes/_authenticated/_admin/relatorios.agendamentos'
import { Route as AuthenticatedAdminAdminVendedoresRouteImport } from './routes/_authenticated/_admin/admin.vendedores'
import { Route as AuthenticatedAdminAdminMovimentacaoLinksRouteImport } from './routes/_authenticated/_admin/admin.movimentacao-links'
import { Route as AuthenticatedAdminAdminFilaRouteImport } from './routes/_authenticated/_admin/admin.fila'
import { Route as AuthenticatedAdminAdminEquipeRouteImport } from './routes/_authenticated/_admin/admin.equipe'
import { Route as AuthenticatedMovimentacaoHistoricoIdEditarRouteImport } from './routes/_authenticated/movimentacao.historico.$id.editar'
import { Route as AuthenticatedAdminAdminMovimentacaoNovoRouteImport } from './routes/_authenticated/_admin/admin.movimentacao.novo'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TotemIndexRoute = TotemIndexRouteImport.update({
  id: '/totem/',
  path: '/totem/',
  getParentRoute: () => rootRouteImport,
} as any)
const TotemProntoRoute = TotemProntoRouteImport.update({
  id: '/totem/pronto',
  path: '/totem/pronto',
  getParentRoute: () => rootRouteImport,
} as any)
const TotemConfirmarRoute = TotemConfirmarRouteImport.update({
  id: '/totem/confirmar',
  path: '/totem/confirmar',
  getParentRoute: () => rootRouteImport,
} as any)
const TotemBuscarRoute = TotemBuscarRouteImport.update({
  id: '/totem/buscar',
  path: '/totem/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const MovimentacaoHistoricoRoute = MovimentacaoHistoricoRouteImport.update({
  id: '/movimentacao/historico',
  path: '/movimentacao/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const MovimentacaoSlugRoute = MovimentacaoSlugRouteImport.update({
  id: '/movimentacao/$slug',
  path: '/movimentacao/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUpdatePasswordRoute = AuthUpdatePasswordRouteImport.update({
  id: '/auth_/update-password',
  path: '/auth/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRecoverRoute = AuthRecoverRouteImport.update({
  id: '/auth_/recover',
  path: '/auth/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const ATokenRoute = ATokenRouteImport.update({
  id: '/a/$token',
  path: '/a/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedServicesRoute = AuthenticatedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewsRoute = AuthenticatedReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMenuRoute = AuthenticatedMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMovimentacaoIndexRoute =
  AuthenticatedMovimentacaoIndexRouteImport.update({
    id: '/movimentacao/',
    path: '/movimentacao/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRelatoriosMovimentacoesRoute =
  AuthenticatedRelatoriosMovimentacoesRouteImport.update({
    id: '/relatorios/movimentacoes',
    path: '/relatorios/movimentacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingServicosRoute =
  AuthenticatedOnboardingServicosRouteImport.update({
    id: '/servicos',
    path: '/servicos',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedOnboardingProntoRoute =
  AuthenticatedOnboardingProntoRouteImport.update({
    id: '/pronto',
    path: '/pronto',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedOnboardingPerfilRoute =
  AuthenticatedOnboardingPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedOnboardingDisponibilidadeRoute =
  AuthenticatedOnboardingDisponibilidadeRouteImport.update({
    id: '/disponibilidade',
    path: '/disponibilidade',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedOnboardingBemVindoRoute =
  AuthenticatedOnboardingBemVindoRouteImport.update({
    id: '/bem-vindo',
    path: '/bem-vindo',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedAppointmentsNewRoute =
  AuthenticatedAppointmentsNewRouteImport.update({
    id: '/appointments/new',
    path: '/appointments/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminReconciliarRoute =
  AuthenticatedAdminReconciliarRouteImport.update({
    id: '/reconciliar',
    path: '/reconciliar',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminGhlTestRoute =
  AuthenticatedAdminGhlTestRouteImport.update({
    id: '/ghl-test',
    path: '/ghl-test',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAppointmentsNewIndexRoute =
  AuthenticatedAppointmentsNewIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppointmentsNewRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncGhlRoute = ApiPublicHooksSyncGhlRouteImport.update({
  id: '/api/public/hooks/sync-ghl',
  path: '/api/public/hooks/sync-ghl',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSendRemindersRoute =
  ApiPublicHooksSendRemindersRouteImport.update({
    id: '/api/public/hooks/send-reminders',
    path: '/api/public/hooks/send-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppointmentsNewServicosRoute =
  AuthenticatedAppointmentsNewServicosRouteImport.update({
    id: '/servicos',
    path: '/servicos',
    getParentRoute: () => AuthenticatedAppointmentsNewRoute,
  } as any)
const AuthenticatedAppointmentsNewRevisaoRoute =
  AuthenticatedAppointmentsNewRevisaoRouteImport.update({
    id: '/revisao',
    path: '/revisao',
    getParentRoute: () => AuthenticatedAppointmentsNewRoute,
  } as any)
const AuthenticatedAppointmentsNewClienteRoute =
  AuthenticatedAppointmentsNewClienteRouteImport.update({
    id: '/cliente',
    path: '/cliente',
    getParentRoute: () => AuthenticatedAppointmentsNewRoute,
  } as any)
const AuthenticatedAppointmentsNewAgendaRoute =
  AuthenticatedAppointmentsNewAgendaRouteImport.update({
    id: '/agenda',
    path: '/agenda',
    getParentRoute: () => AuthenticatedAppointmentsNewRoute,
  } as any)
const AuthenticatedAdminRelatoriosAgendamentosRoute =
  AuthenticatedAdminRelatoriosAgendamentosRouteImport.update({
    id: '/relatorios/agendamentos',
    path: '/relatorios/agendamentos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminVendedoresRoute =
  AuthenticatedAdminAdminVendedoresRouteImport.update({
    id: '/admin/vendedores',
    path: '/admin/vendedores',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminMovimentacaoLinksRoute =
  AuthenticatedAdminAdminMovimentacaoLinksRouteImport.update({
    id: '/admin/movimentacao-links',
    path: '/admin/movimentacao-links',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminFilaRoute =
  AuthenticatedAdminAdminFilaRouteImport.update({
    id: '/admin/fila',
    path: '/admin/fila',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminEquipeRoute =
  AuthenticatedAdminAdminEquipeRouteImport.update({
    id: '/admin/equipe',
    path: '/admin/equipe',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedMovimentacaoHistoricoIdEditarRoute =
  AuthenticatedMovimentacaoHistoricoIdEditarRouteImport.update({
    id: '/movimentacao/historico/$id/editar',
    path: '/movimentacao/historico/$id/editar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAdminMovimentacaoNovoRoute =
  AuthenticatedAdminAdminMovimentacaoNovoRouteImport.update({
    id: '/admin/movimentacao/novo',
    path: '/admin/movimentacao/novo',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/home': typeof AuthenticatedHomeRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/reviews': typeof AuthenticatedReviewsRoute
  '/services': typeof AuthenticatedServicesRoute
  '/a/$token': typeof ATokenRoute
  '/auth/recover': typeof AuthRecoverRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/movimentacao/$slug': typeof MovimentacaoSlugRoute
  '/movimentacao/historico': typeof MovimentacaoHistoricoRoute
  '/totem/buscar': typeof TotemBuscarRoute
  '/totem/confirmar': typeof TotemConfirmarRoute
  '/totem/pronto': typeof TotemProntoRoute
  '/totem/': typeof TotemIndexRoute
  '/ghl-test': typeof AuthenticatedAdminGhlTestRoute
  '/reconciliar': typeof AuthenticatedAdminReconciliarRoute
  '/appointments/new': typeof AuthenticatedAppointmentsNewRouteWithChildren
  '/onboarding/bem-vindo': typeof AuthenticatedOnboardingBemVindoRoute
  '/onboarding/disponibilidade': typeof AuthenticatedOnboardingDisponibilidadeRoute
  '/onboarding/perfil': typeof AuthenticatedOnboardingPerfilRoute
  '/onboarding/pronto': typeof AuthenticatedOnboardingProntoRoute
  '/onboarding/servicos': typeof AuthenticatedOnboardingServicosRoute
  '/relatorios/movimentacoes': typeof AuthenticatedRelatoriosMovimentacoesRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/movimentacao/': typeof AuthenticatedMovimentacaoIndexRoute
  '/admin/equipe': typeof AuthenticatedAdminAdminEquipeRoute
  '/admin/fila': typeof AuthenticatedAdminAdminFilaRoute
  '/admin/movimentacao-links': typeof AuthenticatedAdminAdminMovimentacaoLinksRoute
  '/admin/vendedores': typeof AuthenticatedAdminAdminVendedoresRoute
  '/relatorios/agendamentos': typeof AuthenticatedAdminRelatoriosAgendamentosRoute
  '/appointments/new/agenda': typeof AuthenticatedAppointmentsNewAgendaRoute
  '/appointments/new/cliente': typeof AuthenticatedAppointmentsNewClienteRoute
  '/appointments/new/revisao': typeof AuthenticatedAppointmentsNewRevisaoRoute
  '/appointments/new/servicos': typeof AuthenticatedAppointmentsNewServicosRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
  '/api/public/hooks/sync-ghl': typeof ApiPublicHooksSyncGhlRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/appointments/new/': typeof AuthenticatedAppointmentsNewIndexRoute
  '/admin/movimentacao/novo': typeof AuthenticatedAdminAdminMovimentacaoNovoRoute
  '/movimentacao/historico/$id/editar': typeof AuthenticatedMovimentacaoHistoricoIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/home': typeof AuthenticatedHomeRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/reviews': typeof AuthenticatedReviewsRoute
  '/services': typeof AuthenticatedServicesRoute
  '/a/$token': typeof ATokenRoute
  '/auth/recover': typeof AuthRecoverRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/movimentacao/$slug': typeof MovimentacaoSlugRoute
  '/movimentacao/historico': typeof MovimentacaoHistoricoRoute
  '/totem/buscar': typeof TotemBuscarRoute
  '/totem/confirmar': typeof TotemConfirmarRoute
  '/totem/pronto': typeof TotemProntoRoute
  '/totem': typeof TotemIndexRoute
  '/ghl-test': typeof AuthenticatedAdminGhlTestRoute
  '/reconciliar': typeof AuthenticatedAdminReconciliarRoute
  '/onboarding/bem-vindo': typeof AuthenticatedOnboardingBemVindoRoute
  '/onboarding/disponibilidade': typeof AuthenticatedOnboardingDisponibilidadeRoute
  '/onboarding/perfil': typeof AuthenticatedOnboardingPerfilRoute
  '/onboarding/pronto': typeof AuthenticatedOnboardingProntoRoute
  '/onboarding/servicos': typeof AuthenticatedOnboardingServicosRoute
  '/relatorios/movimentacoes': typeof AuthenticatedRelatoriosMovimentacoesRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/movimentacao': typeof AuthenticatedMovimentacaoIndexRoute
  '/admin/equipe': typeof AuthenticatedAdminAdminEquipeRoute
  '/admin/fila': typeof AuthenticatedAdminAdminFilaRoute
  '/admin/movimentacao-links': typeof AuthenticatedAdminAdminMovimentacaoLinksRoute
  '/admin/vendedores': typeof AuthenticatedAdminAdminVendedoresRoute
  '/relatorios/agendamentos': typeof AuthenticatedAdminRelatoriosAgendamentosRoute
  '/appointments/new/agenda': typeof AuthenticatedAppointmentsNewAgendaRoute
  '/appointments/new/cliente': typeof AuthenticatedAppointmentsNewClienteRoute
  '/appointments/new/revisao': typeof AuthenticatedAppointmentsNewRevisaoRoute
  '/appointments/new/servicos': typeof AuthenticatedAppointmentsNewServicosRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
  '/api/public/hooks/sync-ghl': typeof ApiPublicHooksSyncGhlRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/appointments/new': typeof AuthenticatedAppointmentsNewIndexRoute
  '/admin/movimentacao/novo': typeof AuthenticatedAdminAdminMovimentacaoNovoRoute
  '/movimentacao/historico/$id/editar': typeof AuthenticatedMovimentacaoHistoricoIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/menu': typeof AuthenticatedMenuRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/_authenticated/reviews': typeof AuthenticatedReviewsRoute
  '/_authenticated/services': typeof AuthenticatedServicesRoute
  '/a/$token': typeof ATokenRoute
  '/auth_/recover': typeof AuthRecoverRoute
  '/auth_/update-password': typeof AuthUpdatePasswordRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/movimentacao/$slug': typeof MovimentacaoSlugRoute
  '/movimentacao/historico': typeof MovimentacaoHistoricoRoute
  '/totem/buscar': typeof TotemBuscarRoute
  '/totem/confirmar': typeof TotemConfirmarRoute
  '/totem/pronto': typeof TotemProntoRoute
  '/totem/': typeof TotemIndexRoute
  '/_authenticated/_admin/ghl-test': typeof AuthenticatedAdminGhlTestRoute
  '/_authenticated/_admin/reconciliar': typeof AuthenticatedAdminReconciliarRoute
  '/_authenticated/appointments/new': typeof AuthenticatedAppointmentsNewRouteWithChildren
  '/_authenticated/onboarding/bem-vindo': typeof AuthenticatedOnboardingBemVindoRoute
  '/_authenticated/onboarding/disponibilidade': typeof AuthenticatedOnboardingDisponibilidadeRoute
  '/_authenticated/onboarding/perfil': typeof AuthenticatedOnboardingPerfilRoute
  '/_authenticated/onboarding/pronto': typeof AuthenticatedOnboardingProntoRoute
  '/_authenticated/onboarding/servicos': typeof AuthenticatedOnboardingServicosRoute
  '/_authenticated/relatorios/movimentacoes': typeof AuthenticatedRelatoriosMovimentacoesRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/movimentacao/': typeof AuthenticatedMovimentacaoIndexRoute
  '/_authenticated/_admin/admin/equipe': typeof AuthenticatedAdminAdminEquipeRoute
  '/_authenticated/_admin/admin/fila': typeof AuthenticatedAdminAdminFilaRoute
  '/_authenticated/_admin/admin/movimentacao-links': typeof AuthenticatedAdminAdminMovimentacaoLinksRoute
  '/_authenticated/_admin/admin/vendedores': typeof AuthenticatedAdminAdminVendedoresRoute
  '/_authenticated/_admin/relatorios/agendamentos': typeof AuthenticatedAdminRelatoriosAgendamentosRoute
  '/_authenticated/appointments/new/agenda': typeof AuthenticatedAppointmentsNewAgendaRoute
  '/_authenticated/appointments/new/cliente': typeof AuthenticatedAppointmentsNewClienteRoute
  '/_authenticated/appointments/new/revisao': typeof AuthenticatedAppointmentsNewRevisaoRoute
  '/_authenticated/appointments/new/servicos': typeof AuthenticatedAppointmentsNewServicosRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
  '/api/public/hooks/sync-ghl': typeof ApiPublicHooksSyncGhlRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/_authenticated/appointments/new/': typeof AuthenticatedAppointmentsNewIndexRoute
  '/_authenticated/_admin/admin/movimentacao/novo': typeof AuthenticatedAdminAdminMovimentacaoNovoRoute
  '/_authenticated/movimentacao/historico/$id/editar': typeof AuthenticatedMovimentacaoHistoricoIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/unsubscribe'
    | '/agenda'
    | '/financeiro'
    | '/home'
    | '/menu'
    | '/onboarding'
    | '/reviews'
    | '/services'
    | '/a/$token'
    | '/auth/recover'
    | '/auth/update-password'
    | '/email/unsubscribe'
    | '/movimentacao/$slug'
    | '/movimentacao/historico'
    | '/totem/buscar'
    | '/totem/confirmar'
    | '/totem/pronto'
    | '/totem/'
    | '/ghl-test'
    | '/reconciliar'
    | '/appointments/new'
    | '/onboarding/bem-vindo'
    | '/onboarding/disponibilidade'
    | '/onboarding/perfil'
    | '/onboarding/pronto'
    | '/onboarding/servicos'
    | '/relatorios/movimentacoes'
    | '/lovable/email/suppression'
    | '/movimentacao/'
    | '/admin/equipe'
    | '/admin/fila'
    | '/admin/movimentacao-links'
    | '/admin/vendedores'
    | '/relatorios/agendamentos'
    | '/appointments/new/agenda'
    | '/appointments/new/cliente'
    | '/appointments/new/revisao'
    | '/appointments/new/servicos'
    | '/api/public/hooks/send-reminders'
    | '/api/public/hooks/sync-ghl'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/appointments/new/'
    | '/admin/movimentacao/novo'
    | '/movimentacao/historico/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/unsubscribe'
    | '/agenda'
    | '/financeiro'
    | '/home'
    | '/menu'
    | '/onboarding'
    | '/reviews'
    | '/services'
    | '/a/$token'
    | '/auth/recover'
    | '/auth/update-password'
    | '/email/unsubscribe'
    | '/movimentacao/$slug'
    | '/movimentacao/historico'
    | '/totem/buscar'
    | '/totem/confirmar'
    | '/totem/pronto'
    | '/totem'
    | '/ghl-test'
    | '/reconciliar'
    | '/onboarding/bem-vindo'
    | '/onboarding/disponibilidade'
    | '/onboarding/perfil'
    | '/onboarding/pronto'
    | '/onboarding/servicos'
    | '/relatorios/movimentacoes'
    | '/lovable/email/suppression'
    | '/movimentacao'
    | '/admin/equipe'
    | '/admin/fila'
    | '/admin/movimentacao-links'
    | '/admin/vendedores'
    | '/relatorios/agendamentos'
    | '/appointments/new/agenda'
    | '/appointments/new/cliente'
    | '/appointments/new/revisao'
    | '/appointments/new/servicos'
    | '/api/public/hooks/send-reminders'
    | '/api/public/hooks/sync-ghl'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/appointments/new'
    | '/admin/movimentacao/novo'
    | '/movimentacao/historico/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/unsubscribe'
    | '/_authenticated/_admin'
    | '/_authenticated/agenda'
    | '/_authenticated/financeiro'
    | '/_authenticated/home'
    | '/_authenticated/menu'
    | '/_authenticated/onboarding'
    | '/_authenticated/reviews'
    | '/_authenticated/services'
    | '/a/$token'
    | '/auth_/recover'
    | '/auth_/update-password'
    | '/email/unsubscribe'
    | '/movimentacao/$slug'
    | '/movimentacao/historico'
    | '/totem/buscar'
    | '/totem/confirmar'
    | '/totem/pronto'
    | '/totem/'
    | '/_authenticated/_admin/ghl-test'
    | '/_authenticated/_admin/reconciliar'
    | '/_authenticated/appointments/new'
    | '/_authenticated/onboarding/bem-vindo'
    | '/_authenticated/onboarding/disponibilidade'
    | '/_authenticated/onboarding/perfil'
    | '/_authenticated/onboarding/pronto'
    | '/_authenticated/onboarding/servicos'
    | '/_authenticated/relatorios/movimentacoes'
    | '/lovable/email/suppression'
    | '/_authenticated/movimentacao/'
    | '/_authenticated/_admin/admin/equipe'
    | '/_authenticated/_admin/admin/fila'
    | '/_authenticated/_admin/admin/movimentacao-links'
    | '/_authenticated/_admin/admin/vendedores'
    | '/_authenticated/_admin/relatorios/agendamentos'
    | '/_authenticated/appointments/new/agenda'
    | '/_authenticated/appointments/new/cliente'
    | '/_authenticated/appointments/new/revisao'
    | '/_authenticated/appointments/new/servicos'
    | '/api/public/hooks/send-reminders'
    | '/api/public/hooks/sync-ghl'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/_authenticated/appointments/new/'
    | '/_authenticated/_admin/admin/movimentacao/novo'
    | '/_authenticated/movimentacao/historico/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  ATokenRoute: typeof ATokenRoute
  AuthRecoverRoute: typeof AuthRecoverRoute
  AuthUpdatePasswordRoute: typeof AuthUpdatePasswordRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  MovimentacaoSlugRoute: typeof MovimentacaoSlugRoute
  MovimentacaoHistoricoRoute: typeof MovimentacaoHistoricoRoute
  TotemBuscarRoute: typeof TotemBuscarRoute
  TotemConfirmarRoute: typeof TotemConfirmarRoute
  TotemProntoRoute: typeof TotemProntoRoute
  TotemIndexRoute: typeof TotemIndexRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksSendRemindersRoute: typeof ApiPublicHooksSendRemindersRoute
  ApiPublicHooksSyncGhlRoute: typeof ApiPublicHooksSyncGhlRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/totem/': {
      id: '/totem/'
      path: '/totem'
      fullPath: '/totem/'
      preLoaderRoute: typeof TotemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/totem/pronto': {
      id: '/totem/pronto'
      path: '/totem/pronto'
      fullPath: '/totem/pronto'
      preLoaderRoute: typeof TotemProntoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/totem/confirmar': {
      id: '/totem/confirmar'
      path: '/totem/confirmar'
      fullPath: '/totem/confirmar'
      preLoaderRoute: typeof TotemConfirmarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/totem/buscar': {
      id: '/totem/buscar'
      path: '/totem/buscar'
      fullPath: '/totem/buscar'
      preLoaderRoute: typeof TotemBuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movimentacao/historico': {
      id: '/movimentacao/historico'
      path: '/movimentacao/historico'
      fullPath: '/movimentacao/historico'
      preLoaderRoute: typeof MovimentacaoHistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movimentacao/$slug': {
      id: '/movimentacao/$slug'
      path: '/movimentacao/$slug'
      fullPath: '/movimentacao/$slug'
      preLoaderRoute: typeof MovimentacaoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/update-password': {
      id: '/auth_/update-password'
      path: '/auth/update-password'
      fullPath: '/auth/update-password'
      preLoaderRoute: typeof AuthUpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/recover': {
      id: '/auth_/recover'
      path: '/auth/recover'
      fullPath: '/auth/recover'
      preLoaderRoute: typeof AuthRecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$token': {
      id: '/a/$token'
      path: '/a/$token'
      fullPath: '/a/$token'
      preLoaderRoute: typeof ATokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/services': {
      id: '/_authenticated/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reviews': {
      id: '/_authenticated/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthenticatedReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menu': {
      id: '/_authenticated/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AuthenticatedMenuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movimentacao/': {
      id: '/_authenticated/movimentacao/'
      path: '/movimentacao'
      fullPath: '/movimentacao/'
      preLoaderRoute: typeof AuthenticatedMovimentacaoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/relatorios/movimentacoes': {
      id: '/_authenticated/relatorios/movimentacoes'
      path: '/relatorios/movimentacoes'
      fullPath: '/relatorios/movimentacoes'
      preLoaderRoute: typeof AuthenticatedRelatoriosMovimentacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/servicos': {
      id: '/_authenticated/onboarding/servicos'
      path: '/servicos'
      fullPath: '/onboarding/servicos'
      preLoaderRoute: typeof AuthenticatedOnboardingServicosRouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/onboarding/pronto': {
      id: '/_authenticated/onboarding/pronto'
      path: '/pronto'
      fullPath: '/onboarding/pronto'
      preLoaderRoute: typeof AuthenticatedOnboardingProntoRouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/onboarding/perfil': {
      id: '/_authenticated/onboarding/perfil'
      path: '/perfil'
      fullPath: '/onboarding/perfil'
      preLoaderRoute: typeof AuthenticatedOnboardingPerfilRouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/onboarding/disponibilidade': {
      id: '/_authenticated/onboarding/disponibilidade'
      path: '/disponibilidade'
      fullPath: '/onboarding/disponibilidade'
      preLoaderRoute: typeof AuthenticatedOnboardingDisponibilidadeRouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/onboarding/bem-vindo': {
      id: '/_authenticated/onboarding/bem-vindo'
      path: '/bem-vindo'
      fullPath: '/onboarding/bem-vindo'
      preLoaderRoute: typeof AuthenticatedOnboardingBemVindoRouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/appointments/new': {
      id: '/_authenticated/appointments/new'
      path: '/appointments/new'
      fullPath: '/appointments/new'
      preLoaderRoute: typeof AuthenticatedAppointmentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin/reconciliar': {
      id: '/_authenticated/_admin/reconciliar'
      path: '/reconciliar'
      fullPath: '/reconciliar'
      preLoaderRoute: typeof AuthenticatedAdminReconciliarRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/ghl-test': {
      id: '/_authenticated/_admin/ghl-test'
      path: '/ghl-test'
      fullPath: '/ghl-test'
      preLoaderRoute: typeof AuthenticatedAdminGhlTestRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/appointments/new/': {
      id: '/_authenticated/appointments/new/'
      path: '/'
      fullPath: '/appointments/new/'
      preLoaderRoute: typeof AuthenticatedAppointmentsNewIndexRouteImport
      parentRoute: typeof AuthenticatedAppointmentsNewRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-ghl': {
      id: '/api/public/hooks/sync-ghl'
      path: '/api/public/hooks/sync-ghl'
      fullPath: '/api/public/hooks/sync-ghl'
      preLoaderRoute: typeof ApiPublicHooksSyncGhlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-reminders': {
      id: '/api/public/hooks/send-reminders'
      path: '/api/public/hooks/send-reminders'
      fullPath: '/api/public/hooks/send-reminders'
      preLoaderRoute: typeof ApiPublicHooksSendRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/appointments/new/servicos': {
      id: '/_authenticated/appointments/new/servicos'
      path: '/servicos'
      fullPath: '/appointments/new/servicos'
      preLoaderRoute: typeof AuthenticatedAppointmentsNewServicosRouteImport
      parentRoute: typeof AuthenticatedAppointmentsNewRoute
    }
    '/_authenticated/appointments/new/revisao': {
      id: '/_authenticated/appointments/new/revisao'
      path: '/revisao'
      fullPath: '/appointments/new/revisao'
      preLoaderRoute: typeof AuthenticatedAppointmentsNewRevisaoRouteImport
      parentRoute: typeof AuthenticatedAppointmentsNewRoute
    }
    '/_authenticated/appointments/new/cliente': {
      id: '/_authenticated/appointments/new/cliente'
      path: '/cliente'
      fullPath: '/appointments/new/cliente'
      preLoaderRoute: typeof AuthenticatedAppointmentsNewClienteRouteImport
      parentRoute: typeof AuthenticatedAppointmentsNewRoute
    }
    '/_authenticated/appointments/new/agenda': {
      id: '/_authenticated/appointments/new/agenda'
      path: '/agenda'
      fullPath: '/appointments/new/agenda'
      preLoaderRoute: typeof AuthenticatedAppointmentsNewAgendaRouteImport
      parentRoute: typeof AuthenticatedAppointmentsNewRoute
    }
    '/_authenticated/_admin/relatorios/agendamentos': {
      id: '/_authenticated/_admin/relatorios/agendamentos'
      path: '/relatorios/agendamentos'
      fullPath: '/relatorios/agendamentos'
      preLoaderRoute: typeof AuthenticatedAdminRelatoriosAgendamentosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/vendedores': {
      id: '/_authenticated/_admin/admin/vendedores'
      path: '/admin/vendedores'
      fullPath: '/admin/vendedores'
      preLoaderRoute: typeof AuthenticatedAdminAdminVendedoresRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/movimentacao-links': {
      id: '/_authenticated/_admin/admin/movimentacao-links'
      path: '/admin/movimentacao-links'
      fullPath: '/admin/movimentacao-links'
      preLoaderRoute: typeof AuthenticatedAdminAdminMovimentacaoLinksRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/fila': {
      id: '/_authenticated/_admin/admin/fila'
      path: '/admin/fila'
      fullPath: '/admin/fila'
      preLoaderRoute: typeof AuthenticatedAdminAdminFilaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/equipe': {
      id: '/_authenticated/_admin/admin/equipe'
      path: '/admin/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof AuthenticatedAdminAdminEquipeRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/movimentacao/historico/$id/editar': {
      id: '/_authenticated/movimentacao/historico/$id/editar'
      path: '/movimentacao/historico/$id/editar'
      fullPath: '/movimentacao/historico/$id/editar'
      preLoaderRoute: typeof AuthenticatedMovimentacaoHistoricoIdEditarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin/admin/movimentacao/novo': {
      id: '/_authenticated/_admin/admin/movimentacao/novo'
      path: '/admin/movimentacao/novo'
      fullPath: '/admin/movimentacao/novo'
      preLoaderRoute: typeof AuthenticatedAdminAdminMovimentacaoNovoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminGhlTestRoute: typeof AuthenticatedAdminGhlTestRoute
  AuthenticatedAdminReconciliarRoute: typeof AuthenticatedAdminReconciliarRoute
  AuthenticatedAdminAdminEquipeRoute: typeof AuthenticatedAdminAdminEquipeRoute
  AuthenticatedAdminAdminFilaRoute: typeof AuthenticatedAdminAdminFilaRoute
  AuthenticatedAdminAdminMovimentacaoLinksRoute: typeof AuthenticatedAdminAdminMovimentacaoLinksRoute
  AuthenticatedAdminAdminVendedoresRoute: typeof AuthenticatedAdminAdminVendedoresRoute
  AuthenticatedAdminRelatoriosAgendamentosRoute: typeof AuthenticatedAdminRelatoriosAgendamentosRoute
  AuthenticatedAdminAdminMovimentacaoNovoRoute: typeof AuthenticatedAdminAdminMovimentacaoNovoRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminGhlTestRoute: AuthenticatedAdminGhlTestRoute,
    AuthenticatedAdminReconciliarRoute: AuthenticatedAdminReconciliarRoute,
    AuthenticatedAdminAdminEquipeRoute: AuthenticatedAdminAdminEquipeRoute,
    AuthenticatedAdminAdminFilaRoute: AuthenticatedAdminAdminFilaRoute,
    AuthenticatedAdminAdminMovimentacaoLinksRoute:
      AuthenticatedAdminAdminMovimentacaoLinksRoute,
    AuthenticatedAdminAdminVendedoresRoute:
      AuthenticatedAdminAdminVendedoresRoute,
    AuthenticatedAdminRelatoriosAgendamentosRoute:
      AuthenticatedAdminRelatoriosAgendamentosRoute,
    AuthenticatedAdminAdminMovimentacaoNovoRoute:
      AuthenticatedAdminAdminMovimentacaoNovoRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedOnboardingRouteChildren {
  AuthenticatedOnboardingBemVindoRoute: typeof AuthenticatedOnboardingBemVindoRoute
  AuthenticatedOnboardingDisponibilidadeRoute: typeof AuthenticatedOnboardingDisponibilidadeRoute
  AuthenticatedOnboardingPerfilRoute: typeof AuthenticatedOnboardingPerfilRoute
  AuthenticatedOnboardingProntoRoute: typeof AuthenticatedOnboardingProntoRoute
  AuthenticatedOnboardingServicosRoute: typeof AuthenticatedOnboardingServicosRoute
}

const AuthenticatedOnboardingRouteChildren: AuthenticatedOnboardingRouteChildren =
  {
    AuthenticatedOnboardingBemVindoRoute: AuthenticatedOnboardingBemVindoRoute,
    AuthenticatedOnboardingDisponibilidadeRoute:
      AuthenticatedOnboardingDisponibilidadeRoute,
    AuthenticatedOnboardingPerfilRoute: AuthenticatedOnboardingPerfilRoute,
    AuthenticatedOnboardingProntoRoute: AuthenticatedOnboardingProntoRoute,
    AuthenticatedOnboardingServicosRoute: AuthenticatedOnboardingServicosRoute,
  }

const AuthenticatedOnboardingRouteWithChildren =
  AuthenticatedOnboardingRoute._addFileChildren(
    AuthenticatedOnboardingRouteChildren,
  )

interface AuthenticatedAppointmentsNewRouteChildren {
  AuthenticatedAppointmentsNewAgendaRoute: typeof AuthenticatedAppointmentsNewAgendaRoute
  AuthenticatedAppointmentsNewClienteRoute: typeof AuthenticatedAppointmentsNewClienteRoute
  AuthenticatedAppointmentsNewRevisaoRoute: typeof AuthenticatedAppointmentsNewRevisaoRoute
  AuthenticatedAppointmentsNewServicosRoute: typeof AuthenticatedAppointmentsNewServicosRoute
  AuthenticatedAppointmentsNewIndexRoute: typeof AuthenticatedAppointmentsNewIndexRoute
}

const AuthenticatedAppointmentsNewRouteChildren: AuthenticatedAppointmentsNewRouteChildren =
  {
    AuthenticatedAppointmentsNewAgendaRoute:
      AuthenticatedAppointmentsNewAgendaRoute,
    AuthenticatedAppointmentsNewClienteRoute:
      AuthenticatedAppointmentsNewClienteRoute,
    AuthenticatedAppointmentsNewRevisaoRoute:
      AuthenticatedAppointmentsNewRevisaoRoute,
    AuthenticatedAppointmentsNewServicosRoute:
      AuthenticatedAppointmentsNewServicosRoute,
    AuthenticatedAppointmentsNewIndexRoute:
      AuthenticatedAppointmentsNewIndexRoute,
  }

const AuthenticatedAppointmentsNewRouteWithChildren =
  AuthenticatedAppointmentsNewRoute._addFileChildren(
    AuthenticatedAppointmentsNewRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMenuRoute: typeof AuthenticatedMenuRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRouteWithChildren
  AuthenticatedReviewsRoute: typeof AuthenticatedReviewsRoute
  AuthenticatedServicesRoute: typeof AuthenticatedServicesRoute
  AuthenticatedAppointmentsNewRoute: typeof AuthenticatedAppointmentsNewRouteWithChildren
  AuthenticatedRelatoriosMovimentacoesRoute: typeof AuthenticatedRelatoriosMovimentacoesRoute
  AuthenticatedMovimentacaoIndexRoute: typeof AuthenticatedMovimentacaoIndexRoute
  AuthenticatedMovimentacaoHistoricoIdEditarRoute: typeof AuthenticatedMovimentacaoHistoricoIdEditarRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMenuRoute: AuthenticatedMenuRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRouteWithChildren,
  AuthenticatedReviewsRoute: AuthenticatedReviewsRoute,
  AuthenticatedServicesRoute: AuthenticatedServicesRoute,
  AuthenticatedAppointmentsNewRoute:
    AuthenticatedAppointmentsNewRouteWithChildren,
  AuthenticatedRelatoriosMovimentacoesRoute:
    AuthenticatedRelatoriosMovimentacoesRoute,
  AuthenticatedMovimentacaoIndexRoute: AuthenticatedMovimentacaoIndexRoute,
  AuthenticatedMovimentacaoHistoricoIdEditarRoute:
    AuthenticatedMovimentacaoHistoricoIdEditarRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  ATokenRoute: ATokenRoute,
  AuthRecoverRoute: AuthRecoverRoute,
  AuthUpdatePasswordRoute: AuthUpdatePasswordRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  MovimentacaoSlugRoute: MovimentacaoSlugRoute,
  MovimentacaoHistoricoRoute: MovimentacaoHistoricoRoute,
  TotemBuscarRoute: TotemBuscarRoute,
  TotemConfirmarRoute: TotemConfirmarRoute,
  TotemProntoRoute: TotemProntoRoute,
  TotemIndexRoute: TotemIndexRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksSendRemindersRoute: ApiPublicHooksSendRemindersRoute,
  ApiPublicHooksSyncGhlRoute: ApiPublicHooksSyncGhlRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
