/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthUpdatePasswordRouteImport } from './routes/auth_.update-password'
import { Route as AuthRecoverRouteImport } from './routes/auth_.recover'
import { Route as AuthenticatedServicesRouteImport } from './routes/_authenticated/services'
import { Route as AuthenticatedReviewsRouteImport } from './routes/_authenticated/reviews'
import { Route as AuthenticatedMenuRouteImport } from './routes/_authenticated/menu'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/_admin/route'
import { Route as AuthenticatedAppointmentsNewRouteImport } from './routes/_authenticated/appointments.new'
import { Route as AuthenticatedAdminReconciliarRouteImport } from './routes/_authenticated/_admin/reconciliar'
import { Route as AuthenticatedAdminGhlTestRouteImport } from './routes/_authenticated/_admin/ghl-test'
import { Route as AuthenticatedAppointmentsNewIndexRouteImport } from './routes/_authenticated/appointments.new.index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksSyncGhlRouteImport } from './routes/api/public/hooks/sync-ghl'
import { Route as AuthenticatedAppointmentsNewServicesRouteImport } from './routes/_authenticated/appointments.new.services'
import { Route as AuthenticatedAppointmentsNewCheckoutRouteImport } from './routes/_authenticated/appointments.new.checkout'
import { Route as AuthenticatedAdminRelatoriosAgendamentosRouteImport } from './routes/_authenticated/_admin/relatorios.agendamentos'
import { Route as AuthenticatedAdminAdminEquipeRouteImport } from './routes/_authenticated/_admin/admin.equipe'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUpdatePasswordRoute = AuthUpdatePasswordRouteImport.update({
  id: '/auth_/update-password',
  path: '/auth/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRecoverRoute = AuthRecoverRouteImport.update({
  id: '/auth_/recover',
  path: '/auth/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedServicesRoute = AuthenticatedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewsRoute = AuthenticatedReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMenuRoute = AuthenticatedMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppointmentsNewRoute =
  AuthenticatedAppointmentsNewRouteImport.update({
    id: '/appointments/new',
    path: '/appointments/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminReconciliarRoute =
  AuthenticatedAdminReconciliarRouteImport.update({
    id: '/reconciliar',
    path: '/reconciliar',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminGhlTestRoute =
  AuthenticatedAdminGhlTestRouteImport.update({
    id: '/ghl-test',
    path: '/ghl-test',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAppointmentsNewIndexRoute =
  AuthenticatedAppointmentsNewIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppointmentsNewRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncGhlRoute = ApiPublicHooksSyncGhlRouteImport.update({
  id: '/api/public/hooks/sync-ghl',
  path: '/api/public/hooks/sync-ghl',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppointmentsNewServicesRoute =
  AuthenticatedAppointmentsNewServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAppointmentsNewRoute,
  } as any)
const AuthenticatedAppointmentsNewCheckoutRoute =
  AuthenticatedAppointmentsNewCheckoutRouteImport.update({
    id: '/checkout',
    path: '/checkout',
    getParentRoute: () => AuthenticatedAppointmentsNewRoute,
  } as any)
const AuthenticatedAdminRelatoriosAgendamentosRoute =
  AuthenticatedAdminRelatoriosAgendamentosRouteImport.update({
    id: '/relatorios/agendamentos',
    path: '/relatorios/agendamentos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminEquipeRoute =
  AuthenticatedAdminAdminEquipeRouteImport.update({
    id: '/admin/equipe',
    path: '/admin/equipe',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/services': typeof AuthenticatedServicesRoute
  '/auth/recover': typeof AuthRecoverRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/ghl-test': typeof AuthenticatedAdminGhlTestRoute
  '/reconciliar': typeof AuthenticatedAdminReconciliarRoute
  '/appointments/new': typeof AuthenticatedAppointmentsNewRouteWithChildren
  '/admin/equipe': typeof AuthenticatedAdminAdminEquipeRoute
  '/relatorios/agendamentos': typeof AuthenticatedAdminRelatoriosAgendamentosRoute
  '/appointments/new/checkout': typeof AuthenticatedAppointmentsNewCheckoutRoute
  '/appointments/new/services': typeof AuthenticatedAppointmentsNewServicesRoute
  '/api/public/hooks/sync-ghl': typeof ApiPublicHooksSyncGhlRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/appointments/new/': typeof AuthenticatedAppointmentsNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/services': typeof AuthenticatedServicesRoute
  '/auth/recover': typeof AuthRecoverRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/ghl-test': typeof AuthenticatedAdminGhlTestRoute
  '/reconciliar': typeof AuthenticatedAdminReconciliarRoute
  '/admin/equipe': typeof AuthenticatedAdminAdminEquipeRoute
  '/relatorios/agendamentos': typeof AuthenticatedAdminRelatoriosAgendamentosRoute
  '/appointments/new/checkout': typeof AuthenticatedAppointmentsNewCheckoutRoute
  '/appointments/new/services': typeof AuthenticatedAppointmentsNewServicesRoute
  '/api/public/hooks/sync-ghl': typeof ApiPublicHooksSyncGhlRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/appointments/new': typeof AuthenticatedAppointmentsNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/menu': typeof AuthenticatedMenuRoute
  '/_authenticated/reviews': typeof AuthenticatedReviewsRoute
  '/_authenticated/services': typeof AuthenticatedServicesRoute
  '/auth_/recover': typeof AuthRecoverRoute
  '/auth_/update-password': typeof AuthUpdatePasswordRoute
  '/_authenticated/_admin/ghl-test': typeof AuthenticatedAdminGhlTestRoute
  '/_authenticated/_admin/reconciliar': typeof AuthenticatedAdminReconciliarRoute
  '/_authenticated/appointments/new': typeof AuthenticatedAppointmentsNewRouteWithChildren
  '/_authenticated/_admin/admin/equipe': typeof AuthenticatedAdminAdminEquipeRoute
  '/_authenticated/_admin/relatorios/agendamentos': typeof AuthenticatedAdminRelatoriosAgendamentosRoute
  '/_authenticated/appointments/new/checkout': typeof AuthenticatedAppointmentsNewCheckoutRoute
  '/_authenticated/appointments/new/services': typeof AuthenticatedAppointmentsNewServicesRoute
  '/api/public/hooks/sync-ghl': typeof ApiPublicHooksSyncGhlRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_authenticated/appointments/new/': typeof AuthenticatedAppointmentsNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agenda'
    | '/financeiro'
    | '/menu'
    | '/reviews'
    | '/services'
    | '/auth/recover'
    | '/auth/update-password'
    | '/ghl-test'
    | '/reconciliar'
    | '/appointments/new'
    | '/admin/equipe'
    | '/relatorios/agendamentos'
    | '/appointments/new/checkout'
    | '/appointments/new/services'
    | '/api/public/hooks/sync-ghl'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/appointments/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agenda'
    | '/financeiro'
    | '/menu'
    | '/reviews'
    | '/services'
    | '/auth/recover'
    | '/auth/update-password'
    | '/ghl-test'
    | '/reconciliar'
    | '/admin/equipe'
    | '/relatorios/agendamentos'
    | '/appointments/new/checkout'
    | '/appointments/new/services'
    | '/api/public/hooks/sync-ghl'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/appointments/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_admin'
    | '/_authenticated/agenda'
    | '/_authenticated/financeiro'
    | '/_authenticated/menu'
    | '/_authenticated/reviews'
    | '/_authenticated/services'
    | '/auth_/recover'
    | '/auth_/update-password'
    | '/_authenticated/_admin/ghl-test'
    | '/_authenticated/_admin/reconciliar'
    | '/_authenticated/appointments/new'
    | '/_authenticated/_admin/admin/equipe'
    | '/_authenticated/_admin/relatorios/agendamentos'
    | '/_authenticated/appointments/new/checkout'
    | '/_authenticated/appointments/new/services'
    | '/api/public/hooks/sync-ghl'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/_authenticated/appointments/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AuthRecoverRoute: typeof AuthRecoverRoute
  AuthUpdatePasswordRoute: typeof AuthUpdatePasswordRoute
  ApiPublicHooksSyncGhlRoute: typeof ApiPublicHooksSyncGhlRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/update-password': {
      id: '/auth_/update-password'
      path: '/auth/update-password'
      fullPath: '/auth/update-password'
      preLoaderRoute: typeof AuthUpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/recover': {
      id: '/auth_/recover'
      path: '/auth/recover'
      fullPath: '/auth/recover'
      preLoaderRoute: typeof AuthRecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/services': {
      id: '/_authenticated/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reviews': {
      id: '/_authenticated/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthenticatedReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menu': {
      id: '/_authenticated/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AuthenticatedMenuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appointments/new': {
      id: '/_authenticated/appointments/new'
      path: '/appointments/new'
      fullPath: '/appointments/new'
      preLoaderRoute: typeof AuthenticatedAppointmentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin/reconciliar': {
      id: '/_authenticated/_admin/reconciliar'
      path: '/reconciliar'
      fullPath: '/reconciliar'
      preLoaderRoute: typeof AuthenticatedAdminReconciliarRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/ghl-test': {
      id: '/_authenticated/_admin/ghl-test'
      path: '/ghl-test'
      fullPath: '/ghl-test'
      preLoaderRoute: typeof AuthenticatedAdminGhlTestRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/appointments/new/': {
      id: '/_authenticated/appointments/new/'
      path: '/'
      fullPath: '/appointments/new/'
      preLoaderRoute: typeof AuthenticatedAppointmentsNewIndexRouteImport
      parentRoute: typeof AuthenticatedAppointmentsNewRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-ghl': {
      id: '/api/public/hooks/sync-ghl'
      path: '/api/public/hooks/sync-ghl'
      fullPath: '/api/public/hooks/sync-ghl'
      preLoaderRoute: typeof ApiPublicHooksSyncGhlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/appointments/new/services': {
      id: '/_authenticated/appointments/new/services'
      path: '/services'
      fullPath: '/appointments/new/services'
      preLoaderRoute: typeof AuthenticatedAppointmentsNewServicesRouteImport
      parentRoute: typeof AuthenticatedAppointmentsNewRoute
    }
    '/_authenticated/appointments/new/checkout': {
      id: '/_authenticated/appointments/new/checkout'
      path: '/checkout'
      fullPath: '/appointments/new/checkout'
      preLoaderRoute: typeof AuthenticatedAppointmentsNewCheckoutRouteImport
      parentRoute: typeof AuthenticatedAppointmentsNewRoute
    }
    '/_authenticated/_admin/relatorios/agendamentos': {
      id: '/_authenticated/_admin/relatorios/agendamentos'
      path: '/relatorios/agendamentos'
      fullPath: '/relatorios/agendamentos'
      preLoaderRoute: typeof AuthenticatedAdminRelatoriosAgendamentosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/equipe': {
      id: '/_authenticated/_admin/admin/equipe'
      path: '/admin/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof AuthenticatedAdminAdminEquipeRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminGhlTestRoute: typeof AuthenticatedAdminGhlTestRoute
  AuthenticatedAdminReconciliarRoute: typeof AuthenticatedAdminReconciliarRoute
  AuthenticatedAdminAdminEquipeRoute: typeof AuthenticatedAdminAdminEquipeRoute
  AuthenticatedAdminRelatoriosAgendamentosRoute: typeof AuthenticatedAdminRelatoriosAgendamentosRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminGhlTestRoute: AuthenticatedAdminGhlTestRoute,
    AuthenticatedAdminReconciliarRoute: AuthenticatedAdminReconciliarRoute,
    AuthenticatedAdminAdminEquipeRoute: AuthenticatedAdminAdminEquipeRoute,
    AuthenticatedAdminRelatoriosAgendamentosRoute:
      AuthenticatedAdminRelatoriosAgendamentosRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedAppointmentsNewRouteChildren {
  AuthenticatedAppointmentsNewCheckoutRoute: typeof AuthenticatedAppointmentsNewCheckoutRoute
  AuthenticatedAppointmentsNewServicesRoute: typeof AuthenticatedAppointmentsNewServicesRoute
  AuthenticatedAppointmentsNewIndexRoute: typeof AuthenticatedAppointmentsNewIndexRoute
}

const AuthenticatedAppointmentsNewRouteChildren: AuthenticatedAppointmentsNewRouteChildren =
  {
    AuthenticatedAppointmentsNewCheckoutRoute:
      AuthenticatedAppointmentsNewCheckoutRoute,
    AuthenticatedAppointmentsNewServicesRoute:
      AuthenticatedAppointmentsNewServicesRoute,
    AuthenticatedAppointmentsNewIndexRoute:
      AuthenticatedAppointmentsNewIndexRoute,
  }

const AuthenticatedAppointmentsNewRouteWithChildren =
  AuthenticatedAppointmentsNewRoute._addFileChildren(
    AuthenticatedAppointmentsNewRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedMenuRoute: typeof AuthenticatedMenuRoute
  AuthenticatedReviewsRoute: typeof AuthenticatedReviewsRoute
  AuthenticatedServicesRoute: typeof AuthenticatedServicesRoute
  AuthenticatedAppointmentsNewRoute: typeof AuthenticatedAppointmentsNewRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedMenuRoute: AuthenticatedMenuRoute,
  AuthenticatedReviewsRoute: AuthenticatedReviewsRoute,
  AuthenticatedServicesRoute: AuthenticatedServicesRoute,
  AuthenticatedAppointmentsNewRoute:
    AuthenticatedAppointmentsNewRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AuthRecoverRoute: AuthRecoverRoute,
  AuthUpdatePasswordRoute: AuthUpdatePasswordRoute,
  ApiPublicHooksSyncGhlRoute: ApiPublicHooksSyncGhlRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
